"""added likes model

Revision ID: 31d4e7060cba
Revises: 90169737d1d0
Create Date: 2023-03-26 17:08:17.723668

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31d4e7060cba'
down_revision = '90169737d1d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('likes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('post_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('fk_likes_post_liked_posts', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_likes_post_id_posts'), 'posts', ['post_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('post_liked')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('likes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('post_liked', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint(batch_op.f('fk_likes_post_id_posts'), type_='foreignkey')
        batch_op.create_foreign_key('fk_likes_post_liked_posts', 'posts', ['post_liked'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('post_id')

    # ### end Alembic commands ###
