"""about author added

Revision ID: 38fa816e0322
Revises: ad484c998eeb
Create Date: 2023-03-19 21:27:55.050176

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38fa816e0322'
down_revision = 'ad484c998eeb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_bio', sa.Text(length=50000), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('user_bio')

    # ### end Alembic commands ###
