"""added comments model

Revision ID: 77b81b21a1d8
Revises: 27f2c487864c
Create Date: 2023-03-23 03:54:39.765994

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77b81b21a1d8'
down_revision = '27f2c487864c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(length=500), nullable=False),
    sa.Column('date_posted', sa.DateTime(), nullable=True),
    sa.Column('poster_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], name=op.f('fk_comment_post_id_posts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['poster_id'], ['users.id'], name=op.f('fk_comment_poster_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_comment'))
    )
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.alter_column('poster_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_constraint('fk_posts_poster_id_users', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_posts_poster_id_users'), 'users', ['poster_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_posts_poster_id_users'), type_='foreignkey')
        batch_op.create_foreign_key('fk_posts_poster_id_users', 'users', ['poster_id'], ['id'])
        batch_op.alter_column('poster_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    op.drop_table('comment')
    # ### end Alembic commands ###
