"""completely implemented comments

Revision ID: 90169737d1d0
Revises: 77b81b21a1d8
Create Date: 2023-03-23 05:44:03.566576

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90169737d1d0'
down_revision = '77b81b21a1d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_posts')
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.alter_column('poster_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_constraint('fk_posts_poster_id_users', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_posts_poster_id_users'), 'users', ['poster_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_posts_poster_id_users'), type_='foreignkey')
        batch_op.create_foreign_key('fk_posts_poster_id_users', 'users', ['poster_id'], ['id'])
        batch_op.alter_column('poster_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    op.create_table('_alembic_tmp_posts',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=1000), nullable=False),
    sa.Column('content', sa.TEXT(), nullable=False),
    sa.Column('date_posted', sa.DATETIME(), nullable=True),
    sa.Column('slug', sa.VARCHAR(length=255), nullable=True),
    sa.Column('hidden', sa.BOOLEAN(), nullable=True),
    sa.Column('poster_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['poster_id'], ['users.id'], name='fk_posts_poster_id_users', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
